---

- name: Configure Server
  hosts: all
  remote_user: ec2-user
  become: true
  roles:
    - ruby

- name: Install App
  hosts: all
  remote_user: ec2-user
  become: false
  roles:
    - app
  environment:
    PATH: "/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin"
