---

- name: Clone application from git
  git:
    dest=/home/ec2-user/app
    repo=https://github.com/JoshCheek/ec2-experiment.git
    version=master

- name: Install bundler
  gem:
    name=bundler
    state=present

- name: Bundler Install
  bundler:
    chdir=/home/ec2-user/app
    executable=~/bin/bundler
    state=present
    gemfile=Gemfile

- name: Start Server
  command: >
    chdir=/home/ec2-user/app
    bin/start
